name: Action_Release  
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run:  |
          echo "DATE=$(date +'%y%m%d%H')" >> $GITHUB_ENV
      - name: Checkout
        uses: symbuzzer/fork-checkout-repo@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Creating module zip
        run:  |
          sudo zip -r ${{ github.event.repository.name }}.zip *  
      - name: Create and upload release asset
        uses: symbuzzer/fork-github-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.DATE }}
          name: v${{ env.DATE }}
          body: Please check [changelog](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for changes
          files: ${{ github.event.repository.name }}.zip
          gzip: false
          draft: false
          prerelease: false
          allow_override: true
      - name: Cleanup module zip
        run:  |
          rm ${{ github.event.repository.name }}.zip
